create extension if not exists pgcrypto;

do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where t.typname = 'attendance_action'
      and n.nspname = 'public'
  ) then
    create type attendance_action as enum ('IN', 'OUT');
  end if;
end$$;

create table if not exists branches (
  id bigint generated by default as identity primary key,
  name text not null,
  qr_token uuid not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists employees (
  id bigint generated by default as identity primary key,
  code text not null unique,
  full_name text not null,
  phone text,
  hire_date date,
  termination_date date,
  pin_hash text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists attendance_events (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id),
  branch_id bigint not null references branches(id),
  action attendance_action not null,
  event_time timestamptz not null default now(),
  device_time timestamptz,
  lat numeric(9, 6),
  lng numeric(9, 6),
  accuracy_m integer
);

create index if not exists idx_attendance_employee_time on attendance_events (employee_id, event_time desc);
create index if not exists idx_attendance_branch_time on attendance_events (branch_id, event_time desc);
